name: Kalen's Blog
description: Magento, eCommerce, Software, Businss, Family, and Life
meta_description: "Kalen's Blog - Magento, eCommerce, Software, Business, Family, Life"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
basepath: '/'
domain_name: 'https://kalenjordan.com'
google_analytics: 'UA-131245817-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://kalenjordan.com'
author:         'Kalen Jordan'
